pip install string
pip install threading
pip install pypresence
pip install colorama
pip install itertools
pip install tqdm
pip install discord
pip install dhooks
pip install winreg
pip install socket
pip install pymysql
pip install telnetlib
